site :opscode
cookbook 'yum'
cookbook 'sudo'
cookbook 'git'
cookbook 'sqlite'
cookbook 'mysql'
cookbook 'postgresql'
cookbook 'database'
cookbook 'application_ruby'
cookbook 'zsh'
cookbook 'rvm',     github: 'fnichol/chef-rvm'
cookbook 'ruby_build'
cookbook 'rbenv',   github: 'fnichol/chef-rbenv'
cookbook 'openssh', github: 'fnichol/chef-openssh', branch: 'sshd-config'
