site :opscode
cookbook 'yum'
cookbook 'sudo'
cookbook 'git'
cookbook 'sqlite'
cookbook 'mysql'
cookbook 'application_ruby'
cookbook 'zsh'
cookbook 'rvm',     github: 'fnichol/chef-rvm'
cookbook 'openssh', github: 'fnichol/chef-openssh', branch: 'sshd-config'